@extends('layouts.docs')
@section('title',__('Tools'))
@section('content')
<div class="main-content">
  <section class="section">
    <div class="section-body">
      <ul id="submenu">
        <li><a href="#search">{{ __("Generate Content") }}</a></li>
        <li><a href="#history">{{ __("Content History") }}</a></li>
        <li><a href="#chat">{{ __("AI Chat") }}</a></li>
      </ul>
      <div class="section-header text-center">
        <h1 class="main-header">{{ __("Tools") }} </h1>
      </div>
      <hr  class='main-hr'/>
      <p> {!! __("Everything we configured so far is for content generation. Now it is time to enjoy the hardwork. Search using your query and get your desired result by amazing OpenAI") !!}
      </p>
      <div class="section-header">
        <h1 id="search">{{ __("Generate Content") }}</h1>
      </div>
      <hr />
      <p>{{__("OpenAI API allows for fine-tuning of text generation using various parameters, including creativity, phrase repetition level, and input presence level.")}}</p>
      <p class="text-primary fw-bold">{{__("Creativity refers to the degree of novelty and uniqueness in the generated text. Higher levels of creativity can lead to more original and unexpected results, while lower levels may result in more predictable and conservative text.")}}</p>
      <p class="text-warning fw-bold">{{__("Phrase repetition level refers to the frequency of repeating phrases in the generated text. Setting a high penalty for phrase repetition can reduce the occurrence of repetitive phrases in the output, while setting a lower penalty can result in more repetitions.")}}</p>
      <p class="text-success fw-bold">{{__("Input presence level refers to how much the generated text is influenced by the input text provided. A high input presence level ensures that the generated text is closely related to the input, while a lower input presence level allows for more divergence from the input text.")}}</p>
      <p class="fw-bold">{{__("You can think of tokens as pieces of words used for natural language processing. For English text, 1 token is approximately 4 characters or 0.75 words. As a point of reference, the collected works of Shakespeare are about 900,000 words or 1.2M tokens.")}}</p>
      
      
      <img src="{{asset('assets/docs/images/tools1.png')}}" class="img-fluid img-thumbnail mb-4"/>
      <img src="{{asset('assets/docs/images/tools2.png')}}" class="img-fluid img-thumbnail"/>

      <div class="section-header">
        <h1 id="history">{{ __("Content History") }}</h1>
      </div>
      <hr />
      <p> {{ __("This page contains all the generation history you made. You can re-generate them or can copy/download old content. Please note that media generated by OpenAI have a short time visibiliy. You may come later and find your generated media is no longer there. So we recommend to download generated content after you generate.") }}
      </p>
      <img src="{{asset('assets/docs/images/tools-history.png')}}" class="img-fluid img-thumbnail"/>


       <div class="section-header">
        <h1 id="chat">{{ __("AI Chat") }}</h1>
      </div>
      <hr />
      </p>
      <iframe width="90%" height="600px" src="https://www.youtube.com/embed/ZqIWqb-FTVs" title="AI Chat of AI2PEN" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

    </p>
  </section>
</div>
@endsection
